### ISSUE TITLE
Python version ?

### ISSUE THREAD

**Issue by phongnhhn92** [kwotsin/transfer_learning_tutorial#1]
Which version of python are you using to run this code ? I am using Tensorflow on Windows with python 3.5. A few weeks ago i tried to follow this guide https://github.com/tensorflow/models/tree/master/slim but I can only execute it on python 2.7. Seems like you code quite similar to the guide above.

**Comment by kwotsin** [comment]
Yes I ran this in python 2.7, but my OS is Ubuntu 16.04. The workflow is what I got from reading the source code found in the link you provided, which I find was a very neat workflow. Unfortunately, when I tried to generic image classifier code provided from the models library, the code wasn't able to run so I broke down the source code bit by bit and reconstructed only the things I needed for the projects I do. I would say it's better to learn through diving into the source code as you can see how the Google engineers actually design them.

**Comment by phongnhhn92** [comment]
Thank you for quick reply ! I think you did a good job :D

**Comment by kwotsin** [comment]
Thank you so much for your encouragement! :D
