### ISSUE TITLE
How to write the labels.txt?

### ISSUE THREAD

**Issue by lunasdejavu** [kwotsin/transfer_learning_tutorial#16]
when I compile train_flowers.py
there was an error:
Traceback (most recent call last):
  File "train_flowers.py", line 33, in <module>
    label, string_name = line.split(':')
ValueError: not enough values to unpack (expected 2, got 1)

I set the labels.txt like
1 : Yellowcroaker
2 : notOurFishCropper
3 : pomfret-cropped
4 : thunnus
what is wrong with it?

**Comment by kwotsin** [comment]
This issue has to do with understanding how python works, rather than the code itself -- the error is telling you that `line.split(':')` is giving you only 1 value, but not 2. You should try printing what that line of code give to inspect first.
