### ISSUE TITLE
How can I use the files that are the output of this tutorial to classify a single image?

### ISSUE THREAD

**Issue by neild0** [kwotsin/transfer_learning_tutorial#18]
Like everyone else, I'm left with data, meta, and index files, but I can't figure out how to use these files to classify just a single image.

I'm a newbie with Tensorflow, so a basic answer would be greatly appreciated!

**Comment by kwotsin** [comment]
Try using `/path/to/model.ckpt-13800` as the checkpoint location even though the filename might appear to be `model.ckpt-13800.data-00000-of-00001`
