### ISSUE TITLE
UnknownError: Input/Output Error 

### ISSUE THREAD

**Issue by mukul12** [kwotsin/transfer_learning_tutorial#19]
Hi! I was following your guide on transfer learning since I wanted to implement it on my own dataset.
When I ran it, after some steps, I am persistently getting this error.. 
Kindly let me know how to resolve it.

/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/losses/losses_impl.py:731: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

WARNING:tensorflow:From train_alz.py:207: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
WARNING:tensorflow:From train_alz.py:226: streaming_accuracy (from tensorflow.contrib.metrics.python.ops.metric_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.metrics.accuracy. Note that the order of the labels and predictions arguments has been switched.
WARNING:tensorflow:From train_alz.py:257: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2018-03-13 12:58:03.471697: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-03-13 12:58:03.472282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.17GiB freeMemory: 11.11GiB
2018-03-13 12:58:03.472315: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2018-03-13 12:58:03.749993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10774 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
INFO:tensorflow:Restoring parameters from /content/drive/app/log/model.ckpt-202
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Starting standard services.
INFO:tensorflow:Saving checkpoint to path /content/drive/app/log/model.ckpt
INFO:tensorflow:Starting queue runners.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Epoch 1.0/1
INFO:tensorflow:Current Learning Rate: 0.0002
INFO:tensorflow:Current Streaming Accuracy: 0.0
logits: 
 [[ 0.390966   -0.45528865]
 [ 0.19611153 -0.2771586 ]
 [ 0.3723789  -0.26325732]
 [ 0.25104412 -0.26455274]
 [ 0.18112303 -0.13101362]
 [ 0.29722977 -0.26156056]
 [ 0.36001077 -0.2920575 ]
 [ 0.19284382 -0.29659665]
 [ 0.3931404  -0.3488116 ]
 [ 0.2608421  -0.16697197]
 [ 0.09929308 -0.10392085]
 [ 0.34856573 -0.14461401]
 [ 0.43742967 -0.34236282]
 [ 0.24543124 -0.3380828 ]
 [ 0.30201262 -0.35735092]
 [ 0.452847   -0.3696723 ]
 [ 0.26588187 -0.32089466]
 [ 0.2634747  -0.24695566]
 [ 0.3682     -0.3491458 ]
 [ 0.32025513 -0.31040746]
 [ 0.2997362  -0.2824477 ]
 [ 0.13588724 -0.07790426]
 [ 0.15063035 -0.09512474]
 [ 0.24009264 -0.2981124 ]
 [ 0.13652855 -0.20672432]
 [ 0.3162898  -0.32216516]
 [ 1.388223   -1.8755943 ]
 [ 0.2017616  -0.23009525]
 [ 0.16159095 -0.3134655 ]
 [ 0.33364242 -0.274227  ]
 [ 0.3692241  -0.3140025 ]
 [ 0.37961924 -0.29509106]]
Probabilities: 
 [[0.6997809  0.30021912]
 [0.6161575  0.38384253]
 [0.65376633 0.34623367]
 [0.6261176  0.37388238]
 [0.5774067  0.4225933 ]
 [0.63617265 0.3638274 ]
 [0.65747637 0.3425236 ]
 [0.6199746  0.3800254 ]
 [0.6774225  0.32257745]
 [0.60535157 0.39464843]
 [0.5506294  0.44937062]
 [0.6208552  0.37914476]
 [0.6856354  0.31436458]
 [0.6418756  0.3581244 ]
 [0.6591174  0.34088257]
 [0.6947709  0.30522916]
 [0.64262515 0.35737482]
 [0.6249073  0.37509266]
 [0.6720223  0.3279777 ]
 [0.6526397  0.34736034]
 [0.64156973 0.35843024]
 [0.55324525 0.44675475]
 [0.5611314  0.43886855]
 [0.63139474 0.36860523]
 [0.5849804  0.4150195 ]
 [0.6544041  0.3455959 ]
 [0.9631665  0.03683354]
 [0.606317   0.39368302]
 [0.6165799  0.38342014]
 [0.6474546  0.35254538]
 [0.66445845 0.33554155]
 [0.662557   0.33744293]]
predictions: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Labels:
: [0 0 0 1 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 0 0 1 0 0 1 1 0 1 1 1 0 0]
INFO:tensorflow:global step 212: loss: 1.1660 (10.36 sec/step)
INFO:tensorflow:global step 213: loss: 1.0437 (36.21 sec/step)
INFO:tensorflow:global step 214: loss: 1.0660 (2.66 sec/step)
INFO:tensorflow:global step 215: loss: 1.1729 (2.72 sec/step)
INFO:tensorflow:global step 216: loss: 1.0920 (2.65 sec/step)
INFO:tensorflow:global step 217: loss: 1.0246 (2.77 sec/step)
INFO:tensorflow:global step 218: loss: 1.1273 (3.22 sec/step)
INFO:tensorflow:global step 219: loss: 1.0768 (2.96 sec/step)
INFO:tensorflow:global step 220: loss: 1.1072 (2.61 sec/step)
INFO:tensorflow:global step 221: loss: 1.0079 (2.62 sec/step)
INFO:tensorflow:global step 222: loss: 1.0546 (2.61 sec/step)
INFO:tensorflow:global step 223: loss: 1.1526 (2.63 sec/step)
INFO:tensorflow:global step 224: loss: 1.1774 (2.61 sec/step)
INFO:tensorflow:global step 225: loss: 1.0615 (2.63 sec/step)
INFO:tensorflow:global step 226: loss: 1.2225 (2.62 sec/step)
INFO:tensorflow:global step 227: loss: 1.1922 (2.63 sec/step)
INFO:tensorflow:global step 228: loss: 0.9374 (2.71 sec/step)
INFO:tensorflow:global step 229: loss: 1.1487 (2.63 sec/step)
INFO:tensorflow:global step 230: loss: 1.1996 (2.62 sec/step)
INFO:tensorflow:global step 231: loss: 1.1277 (2.67 sec/step)
INFO:tensorflow:global step 232: loss: 1.0695 (2.62 sec/step)
INFO:tensorflow:global step 233: loss: 1.0415 (2.63 sec/step)
INFO:tensorflow:global_step/sec: 0.183334
INFO:tensorflow:global step 234: loss: 1.0975 (2.64 sec/step)
INFO:tensorflow:global step 235: loss: 1.0874 (2.63 sec/step)
INFO:tensorflow:global step 236: loss: 1.0492 (2.63 sec/step)
INFO:tensorflow:global step 237: loss: 1.0601 (2.62 sec/step)
INFO:tensorflow:global step 238: loss: 0.9987 (2.62 sec/step)
INFO:tensorflow:global step 239: loss: 1.0551 (2.63 sec/step)
INFO:tensorflow:global step 240: loss: 1.0787 (2.63 sec/step)
INFO:tensorflow:global step 241: loss: 1.1399 (2.63 sec/step)
INFO:tensorflow:global step 242: loss: 1.1331 (2.63 sec/step)
INFO:tensorflow:global step 243: loss: 1.1698 (2.65 sec/step)
INFO:tensorflow:global step 244: loss: 1.2579 (2.64 sec/step)
INFO:tensorflow:global step 245: loss: 0.9157 (2.64 sec/step)
INFO:tensorflow:global step 246: loss: 1.0891 (2.62 sec/step)
INFO:tensorflow:global step 247: loss: 1.0873 (2.64 sec/step)
INFO:tensorflow:global step 248: loss: 1.2327 (2.63 sec/step)
INFO:tensorflow:global step 249: loss: 1.0241 (2.63 sec/step)
INFO:tensorflow:global step 250: loss: 0.9981 (2.63 sec/step)
INFO:tensorflow:global step 251: loss: 1.1361 (2.62 sec/step)
INFO:tensorflow:global step 252: loss: 1.1365 (2.62 sec/step)
INFO:tensorflow:global step 253: loss: 1.0260 (3.33 sec/step)
INFO:tensorflow:global step 254: loss: 1.0760 (2.63 sec/step)
INFO:tensorflow:global step 255: loss: 1.0620 (2.64 sec/step)
INFO:tensorflow:global step 256: loss: 0.9445 (2.62 sec/step)
INFO:tensorflow:global step 257: loss: 1.0008 (2.62 sec/step)
INFO:tensorflow:global step 258: loss: 1.0649 (2.65 sec/step)
INFO:tensorflow:global step 259: loss: 1.0324 (2.64 sec/step)
INFO:tensorflow:global step 260: loss: 0.9293 (2.62 sec/step)
INFO:tensorflow:global step 261: loss: 1.0554 (2.65 sec/step)
INFO:tensorflow:global step 262: loss: 1.0520 (2.61 sec/step)
INFO:tensorflow:global step 263: loss: 0.9560 (2.63 sec/step)
INFO:tensorflow:global step 264: loss: 0.9489 (2.64 sec/step)
INFO:tensorflow:global step 265: loss: 1.2756 (2.63 sec/step)
INFO:tensorflow:global step 266: loss: 1.1692 (2.62 sec/step)
INFO:tensorflow:global step 267: loss: 0.9642 (2.62 sec/step)
INFO:tensorflow:global step 268: loss: 1.1805 (2.62 sec/step)
INFO:tensorflow:global step 269: loss: 0.9002 (2.62 sec/step)
INFO:tensorflow:global step 270: loss: 1.0323 (2.62 sec/step)
INFO:tensorflow:global step 271: loss: 1.1099 (2.64 sec/step)
INFO:tensorflow:global step 272: loss: 1.0631 (2.63 sec/step)
INFO:tensorflow:global step 273: loss: 1.1938 (2.64 sec/step)
INFO:tensorflow:global step 274: loss: 1.0271 (2.62 sec/step)
INFO:tensorflow:global step 275: loss: 1.0757 (2.63 sec/step)
INFO:tensorflow:global step 276: loss: 1.0682 (2.64 sec/step)
INFO:tensorflow:global step 277: loss: 1.1326 (2.64 sec/step)
INFO:tensorflow:global_step/sec: 0.366475
INFO:tensorflow:global step 278: loss: 1.1278 (2.64 sec/step)
INFO:tensorflow:global step 279: loss: 1.1442 (2.63 sec/step)
INFO:tensorflow:global step 280: loss: 1.0570 (2.63 sec/step)
INFO:tensorflow:global step 281: loss: 1.0622 (2.65 sec/step)
INFO:tensorflow:global step 282: loss: 1.0390 (2.63 sec/step)
INFO:tensorflow:global step 283: loss: 1.0679 (2.63 sec/step)
INFO:tensorflow:global step 284: loss: 1.0516 (2.63 sec/step)
INFO:tensorflow:global step 285: loss: 1.0004 (2.62 sec/step)
INFO:tensorflow:global step 286: loss: 1.1611 (2.61 sec/step)
INFO:tensorflow:global step 287: loss: 1.0007 (2.62 sec/step)
INFO:tensorflow:global step 288: loss: 1.0110 (2.61 sec/step)
INFO:tensorflow:global step 289: loss: 0.9180 (2.62 sec/step)
INFO:tensorflow:global step 290: loss: 0.9802 (2.62 sec/step)
INFO:tensorflow:global step 291: loss: 0.9764 (2.63 sec/step)
INFO:tensorflow:global step 292: loss: 1.1125 (2.61 sec/step)
INFO:tensorflow:global step 293: loss: 1.1945 (2.63 sec/step)
INFO:tensorflow:global step 294: loss: 1.0703 (2.61 sec/step)
INFO:tensorflow:global step 295: loss: 0.9467 (2.64 sec/step)
INFO:tensorflow:global step 296: loss: 1.0956 (2.62 sec/step)
INFO:tensorflow:global step 297: loss: 1.0210 (2.62 sec/step)
INFO:tensorflow:global step 298: loss: 1.1059 (2.61 sec/step)
INFO:tensorflow:global step 299: loss: 1.0867 (2.63 sec/step)
INFO:tensorflow:global step 300: loss: 0.9882 (2.62 sec/step)
INFO:tensorflow:global step 301: loss: 1.0315 (2.62 sec/step)
INFO:tensorflow:global step 302: loss: 1.1471 (2.63 sec/step)
INFO:tensorflow:global step 303: loss: 0.8937 (2.65 sec/step)
INFO:tensorflow:global step 304: loss: 1.1258 (2.65 sec/step)
INFO:tensorflow:global step 305: loss: 1.1221 (2.63 sec/step)
INFO:tensorflow:global step 306: loss: 0.9856 (2.62 sec/step)
INFO:tensorflow:global step 307: loss: 1.1103 (2.62 sec/step)
INFO:tensorflow:global step 308: loss: 0.9343 (2.63 sec/step)
INFO:tensorflow:global step 309: loss: 1.0796 (2.63 sec/step)
INFO:tensorflow:global step 310: loss: 0.9963 (2.63 sec/step)
INFO:tensorflow:global step 311: loss: 1.0599 (2.63 sec/step)
INFO:tensorflow:global step 312: loss: 0.9646 (2.63 sec/step)
INFO:tensorflow:global step 313: loss: 1.1737 (2.64 sec/step)
INFO:tensorflow:global step 314: loss: 1.0207 (2.63 sec/step)
INFO:tensorflow:global step 315: loss: 1.0296 (2.62 sec/step)
INFO:tensorflow:global step 316: loss: 1.0845 (2.64 sec/step)
INFO:tensorflow:global step 317: loss: 0.9909 (2.62 sec/step)
INFO:tensorflow:global step 318: loss: 1.1818 (2.63 sec/step)
INFO:tensorflow:global step 319: loss: 1.1320 (2.62 sec/step)
INFO:tensorflow:global step 320: loss: 1.0076 (2.63 sec/step)
INFO:tensorflow:global step 321: loss: 1.1933 (2.63 sec/step)
INFO:tensorflow:global_step/sec: 0.366859
INFO:tensorflow:global step 322: loss: 1.0940 (2.64 sec/step)
INFO:tensorflow:global step 323: loss: 0.9568 (2.65 sec/step)
INFO:tensorflow:global step 324: loss: 1.0478 (2.64 sec/step)
INFO:tensorflow:global step 325: loss: 1.0858 (2.62 sec/step)
INFO:tensorflow:global step 326: loss: 1.1083 (2.63 sec/step)
INFO:tensorflow:global step 327: loss: 1.1087 (2.64 sec/step)
INFO:tensorflow:global step 328: loss: 1.1253 (2.62 sec/step)
INFO:tensorflow:global step 329: loss: 1.0707 (2.64 sec/step)
INFO:tensorflow:global step 330: loss: 1.0384 (2.62 sec/step)
INFO:tensorflow:global step 331: loss: 1.1274 (2.63 sec/step)
INFO:tensorflow:global step 332: loss: 1.0456 (2.62 sec/step)
INFO:tensorflow:global step 333: loss: 1.0076 (2.64 sec/step)
INFO:tensorflow:global step 334: loss: 0.9234 (2.63 sec/step)
INFO:tensorflow:global step 335: loss: 1.0679 (2.64 sec/step)
INFO:tensorflow:global step 336: loss: 1.0232 (2.63 sec/step)
INFO:tensorflow:global step 337: loss: 1.0858 (2.61 sec/step)
INFO:tensorflow:global step 338: loss: 1.2137 (2.63 sec/step)
INFO:tensorflow:global step 339: loss: 1.0514 (2.62 sec/step)
INFO:tensorflow:global step 340: loss: 0.9872 (2.63 sec/step)
INFO:tensorflow:global step 341: loss: 1.2556 (2.63 sec/step)
INFO:tensorflow:global step 342: loss: 1.0966 (2.63 sec/step)
INFO:tensorflow:global step 343: loss: 1.1035 (3.21 sec/step)
INFO:tensorflow:global step 344: loss: 0.9896 (2.64 sec/step)
INFO:tensorflow:global step 345: loss: 0.9457 (2.63 sec/step)
INFO:tensorflow:global step 346: loss: 0.9988 (2.63 sec/step)
INFO:tensorflow:global step 347: loss: 1.0911 (2.63 sec/step)
INFO:tensorflow:global step 348: loss: 1.0068 (2.63 sec/step)
INFO:tensorflow:global step 349: loss: 1.1755 (2.63 sec/step)
INFO:tensorflow:global step 350: loss: 1.0673 (2.63 sec/step)
INFO:tensorflow:global step 351: loss: 1.0352 (2.64 sec/step)
INFO:tensorflow:global step 352: loss: 1.0703 (2.64 sec/step)
INFO:tensorflow:global step 353: loss: 1.0696 (2.64 sec/step)
INFO:tensorflow:global step 354: loss: 1.0939 (2.62 sec/step)
INFO:tensorflow:global step 355: loss: 0.9891 (2.62 sec/step)
INFO:tensorflow:global step 356: loss: 0.9528 (2.63 sec/step)
INFO:tensorflow:global step 357: loss: 0.9560 (2.62 sec/step)
INFO:tensorflow:global step 358: loss: 0.9822 (2.63 sec/step)
INFO:tensorflow:global step 359: loss: 0.9218 (2.62 sec/step)
INFO:tensorflow:global step 360: loss: 1.0637 (2.61 sec/step)
INFO:tensorflow:global step 361: loss: 1.0187 (2.63 sec/step)
INFO:tensorflow:global step 362: loss: 1.0093 (2.63 sec/step)
INFO:tensorflow:global step 363: loss: 1.1393 (2.65 sec/step)
INFO:tensorflow:global step 364: loss: 0.9312 (2.63 sec/step)
INFO:tensorflow:global step 365: loss: 0.9443 (2.66 sec/step)
INFO:tensorflow:global_step/sec: 0.366662
INFO:tensorflow:global step 366: loss: 0.9431 (2.62 sec/step)
INFO:tensorflow:global step 367: loss: 1.0542 (2.62 sec/step)
INFO:tensorflow:global step 368: loss: 0.8600 (2.62 sec/step)
INFO:tensorflow:global step 369: loss: 1.0323 (2.63 sec/step)
INFO:tensorflow:global step 370: loss: 1.0610 (2.62 sec/step)
INFO:tensorflow:global step 371: loss: 1.0132 (2.63 sec/step)
INFO:tensorflow:global step 372: loss: 1.0827 (2.62 sec/step)
INFO:tensorflow:global step 373: loss: 1.3068 (2.65 sec/step)
INFO:tensorflow:global step 374: loss: 1.0503 (2.61 sec/step)
INFO:tensorflow:global step 375: loss: 0.8931 (2.62 sec/step)
INFO:tensorflow:global step 376: loss: 0.8584 (2.62 sec/step)
INFO:tensorflow:global step 377: loss: 1.0598 (2.62 sec/step)
INFO:tensorflow:global step 378: loss: 0.9794 (2.62 sec/step)
INFO:tensorflow:global step 379: loss: 1.1428 (2.63 sec/step)
INFO:tensorflow:global step 380: loss: 1.1398 (2.62 sec/step)
INFO:tensorflow:global step 381: loss: 1.0700 (2.61 sec/step)
INFO:tensorflow:global step 382: loss: 0.9613 (2.63 sec/step)
INFO:tensorflow:global step 383: loss: 1.1044 (2.65 sec/step)
INFO:tensorflow:global step 384: loss: 1.0618 (2.64 sec/step)
INFO:tensorflow:global step 385: loss: 0.9081 (2.62 sec/step)
INFO:tensorflow:global step 386: loss: 0.9855 (2.63 sec/step)
INFO:tensorflow:global step 387: loss: 1.0260 (2.64 sec/step)
INFO:tensorflow:global step 388: loss: 0.9812 (2.67 sec/step)
INFO:tensorflow:global step 389: loss: 0.8943 (2.62 sec/step)
INFO:tensorflow:global step 390: loss: 1.0939 (2.64 sec/step)
INFO:tensorflow:global step 391: loss: 1.0230 (2.63 sec/step)
INFO:tensorflow:global step 392: loss: 0.9868 (2.62 sec/step)
INFO:tensorflow:global step 393: loss: 1.0887 (2.63 sec/step)
INFO:tensorflow:global step 394: loss: 1.0332 (2.63 sec/step)
INFO:tensorflow:global step 395: loss: 0.9921 (2.63 sec/step)
INFO:tensorflow:global step 396: loss: 0.9881 (2.63 sec/step)
INFO:tensorflow:global step 397: loss: 1.1466 (2.62 sec/step)
INFO:tensorflow:global step 398: loss: 1.0280 (2.63 sec/step)
INFO:tensorflow:global step 399: loss: 1.1928 (2.62 sec/step)
INFO:tensorflow:global step 400: loss: 1.2401 (2.63 sec/step)
INFO:tensorflow:global step 401: loss: 1.0159 (2.63 sec/step)
INFO:tensorflow:global step 402: loss: 1.1129 (2.62 sec/step)
INFO:tensorflow:global step 403: loss: 1.0318 (2.63 sec/step)
INFO:tensorflow:global step 404: loss: 1.0792 (2.63 sec/step)
INFO:tensorflow:global step 405: loss: 0.9984 (2.62 sec/step)
INFO:tensorflow:global step 406: loss: 1.1533 (2.63 sec/step)
INFO:tensorflow:global step 407: loss: 0.9931 (2.62 sec/step)
INFO:tensorflow:global step 408: loss: 1.1291 (2.63 sec/step)
INFO:tensorflow:global step 409: loss: 1.0902 (2.62 sec/step)
INFO:tensorflow:Saving checkpoint to path /content/drive/app/log/model.ckpt
INFO:tensorflow:global_step/sec: 0.36667
INFO:tensorflow:global step 410: loss: 1.0421 (2.69 sec/step)
INFO:tensorflow:global step 411: loss: 1.0558 (2.64 sec/step)
INFO:tensorflow:global step 412: loss: 1.1632 (2.63 sec/step)
INFO:tensorflow:global step 413: loss: 1.0283 (3.06 sec/step)
INFO:tensorflow:global step 414: loss: 1.0561 (2.69 sec/step)
INFO:tensorflow:global step 415: loss: 0.9693 (2.69 sec/step)
INFO:tensorflow:global step 416: loss: 1.0304 (2.68 sec/step)
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnknownError'>, /content/drive/app/images/train/fmri_train_00001-of-00001.tfrecord; Input/output error
	 [[Node: parallel_read/ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/TFRecordReaderV2, parallel_read/filenames)]]
INFO:tensorflow:global step 417: loss: 0.9838 (2.76 sec/step)
INFO:tensorflow:global step 418: loss: 0.7267 (1.44 sec/step)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_3_batch/fifo_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: batch = QueueDequeueUpToV2[component_types=[DT_FLOAT, DT_UINT8, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch/fifo_queue, batch/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/supervisor.py", line 990, in managed_session
    yield sess
  File "train_alz.py", line 285, in run
    loss, _ = train_step(sess, train_op, sv.global_step)
  File "train_alz.py", line 243, in train_step
    total_loss, global_step_count, _ = sess.run([train_op, global_step, metrics_op])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_3_batch/fifo_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: batch = QueueDequeueUpToV2[component_types=[DT_FLOAT, DT_UINT8, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch/fifo_queue, batch/n)]]

Caused by op 'batch', defined at:
  File "train_alz.py", line 298, in <module>
    run()
  File "train_alz.py", line 184, in run
    images, _, labels = load_batch(dataset, batch_size=batch_size)
  File "train_alz.py", line 168, in load_batch
    allow_smaller_final_batch = True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/input.py", line 989, in batch
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/input.py", line 761, in _batch
    dequeued = queue.dequeue_up_to(batch_size, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 527, in dequeue_up_to
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 2557, in _queue_dequeue_up_to_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): FIFOQueue '_3_batch/fifo_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: batch = QueueDequeueUpToV2[component_types=[DT_FLOAT, DT_UINT8, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch/fifo_queue, batch/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_alz.py", line 298, in <module>
    run()
  File "train_alz.py", line 294, in run
    sv.saver.save(sess, sv.save_path, global_step = sv.global_step)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/supervisor.py", line 1000, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/supervisor.py", line 828, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1259, in _single_operation_run
    None)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: /content/drive/app/images/train/fmri_train_00001-of-00001.tfrecord; Input/output error
	 [[Node: parallel_read/ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/TFRecordReaderV2, parallel_read/filenames)]]

I followed your guide on transfer learning and hence wanted to know, why this error is occuring. Your help is appreciated!

**Comment by kwotsin** [comment]
As the error implies, this is an issue with reading your own dataset's tfrecords. You should first check the integrity of your TFRecords (e.g. see if you can extract the image data from tfrecord -> image tensor -> reading image out in numpy format to verify).
