### ISSUE TITLE
tf.train.import_meta_graph

### ISSUE THREAD

**Issue by NassimaD** [kwotsin/transfer_learning_tutorial#22]
hello, I'm trying to use the same tutorial on my own dataset , by using the MobileNet network , but the name of files is mobilenet_v1_0.75_128.ckpt.data-00000-of-00001 mobilenet_v1_0.75_128.ckpt.index mobilenet_v1_0.75_128.ckpt.meta and when I fit one of these files in the function saver.restore, I got an error , how can I include the instruction of tf.train.import_meta_graph in this code to load the meta graph ? Thanks.

**Comment by kwotsin** [comment]
One way you can try is to load the graph with the model (as usual like in training), but restore the checkpoint. The checkpoint file is a bit tricky - you should try using `mobilenet_v1_0.75_128.ckpt` without the trailing characters to restore the model.
