### ISSUE TITLE
Number of Steps per Epoch not int

### ISSUE THREAD

**Issue by ScheiklP** [kwotsin/transfer_learning_tutorial#8]
Hi,
using your train_flower.py script with my Dataset, an error occurred, that num_steps_per_epoch could not be converted from float to int.

I therefore explicitly casted  num_batches_per_epoch into int, so that line 186 looked like this: 
num_batches_per_epoch = int(dataset.num_samples / batch_size)

**Comment by kwotsin** [comment]
I believe that might have to do with what the batch size is. Nonetheless, it's a good quick fix and I've made the necessary changes. Thank you for raising this up!
